# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.26.2

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Espressomatico
title_separator: "-"
subtitle: "Espressomatico..."
locale: "en"
email: 
description: >- # this means to ignore newlines until "baseurl:"
  Espressomatico
#twitter_username: espressomatico
github_username: Espressomatico
minimal_mistakes_skin: dirt
search: true
search_full_content: true # true, false (default)
search_provider: lunr # lunr (default), algolia
lunr:
  search_within_pages: true
repository: Espressomatico/Espressomatico
breadcrumbs: true
comments:
  provider: false

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Brussels # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - .htaccess
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  #- jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Lucas Placentino"
  avatar : #"/assets/images/bio-photo.jpg"
  bio    : ""
  links:
    #- label: "Website"
    #  icon: "fas fa-fw fa-link"
    #  url: "https://lucas.placentino.be"
    #- label: "Twitter"
    #  icon: "fab fa-fw fa-twitter-square"
    #  url: "https://twitter.com/LucasPlacentino"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/LucasPlacentino"

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Espressomatico/Espressomatico"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      comments: false
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      layout: single
      read_time: false
      author_profile: false
      share: false
      comments: false
      sidebar:
        nav: "docs"

collections:
  docs:
    output: true
    permalink: /:collection/:path/
